# Generated by Django 4.2.19 on 2025-03-26 21:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={'ordering': ('-owner', '-created_at')},
        ),
        migrations.RenameField(
            model_name='favourite',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('owner', 'recipe')},
        ),
    ]
