# Generated by Django 4.2.19 on 2025-03-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='../recipe-default-image_vkkgno', upload_to='recipes/'),
        ),
    ]
